// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ExpenseCategory string

const (
	ExpenseCategoryFood      ExpenseCategory = "food"
	ExpenseCategoryTransport ExpenseCategory = "transport"
	ExpenseCategoryBills     ExpenseCategory = "bills"
	ExpenseCategoryShopping  ExpenseCategory = "shopping"
	ExpenseCategoryIncome    ExpenseCategory = "income"
	ExpenseCategoryTopup     ExpenseCategory = "topup"
	ExpenseCategoryOther     ExpenseCategory = "other"
)

func (e *ExpenseCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseCategory(s)
	case string:
		*e = ExpenseCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseCategory: %T", src)
	}
	return nil
}

type NullExpenseCategory struct {
	ExpenseCategory ExpenseCategory `json:"expense_category"`
	Valid           bool            `json:"valid"` // Valid is true if ExpenseCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseCategory), nil
}

type TransactionStatus string

const (
	TransactionStatusAwaitingPayment TransactionStatus = "awaiting_payment"
	TransactionStatusCrediting       TransactionStatus = "crediting"
	TransactionStatusScheduled       TransactionStatus = "scheduled"
	TransactionStatusCompleted       TransactionStatus = "completed"
	TransactionStatusFailed          TransactionStatus = "failed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type Transaction struct {
	ID               pgtype.UUID         `json:"id"`
	SenderID         pgtype.UUID         `json:"sender_id"`
	ReceiverID       pgtype.UUID         `json:"receiver_id"`
	Amount           int64               `json:"amount"`
	Status           TransactionStatus   `json:"status"`
	Note             pgtype.Text         `json:"note"`
	SenderCategory   NullExpenseCategory `json:"sender_category"`
	ReceiverCategory NullExpenseCategory `json:"receiver_category"`
	ScheduledAt      pgtype.Timestamptz  `json:"scheduled_at"`
	CreatedAt        pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz  `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	Password       string             `json:"password"`
	FullName       string             `json:"full_name"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Balance        int64              `json:"balance"`
	IsSystem       bool               `json:"is_system"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
