// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Races the scheduler correctly: this delete blocks on the scheduler's row
	// lock and then affects zero rows. Whichever lands first wins.
	CancelScheduledTransaction(ctx context.Context, arg CancelScheduledTransactionParams) (Transaction, error)
	ClaimDueTransactions(ctx context.Context, limit int32) ([]Transaction, error)
	ClaimStuckCrediting(ctx context.Context, limit int32) ([]Transaction, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreditUser(ctx context.Context, arg CreditUserParams) (User, error)
	// Zero rows means insufficient funds. This guard, inside the money-moving
	// transaction, is the ONLY thing enforcing sufficient funds -- a read taken
	// outside the transaction protects nothing. The system-account carve-out lives
	// here so callers never have to branch on it.
	DebitUser(ctx context.Context, arg DebitUserParams) (User, error)
	GetBalance(ctx context.Context, id pgtype.UUID) (int64, error)
	GetTransactionById(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionByIdWithUsers(ctx context.Context, id pgtype.UUID) (GetTransactionByIdWithUsersRow, error)
	GetTransactionsByUserId(ctx context.Context, senderID pgtype.UUID) ([]GetTransactionsByUserIdRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByName(ctx context.Context, fullName string) ([]User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	// The whole rewrite in one statement: the status guard makes the update claim
	// the row, and the row lock serializes concurrent callers. Zero rows
	// (pgx.ErrNoRows) means somebody else already did this work.
	GuardedSetStatus(ctx context.Context, arg GuardedSetStatusParams) (Transaction, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SetReceiverCategory(ctx context.Context, arg SetReceiverCategoryParams) (Transaction, error)
	SetSenderCategory(ctx context.Context, arg SetSenderCategoryParams) (Transaction, error)
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (User, error)
}

var _ Querier = (*Queries)(nil)
