// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_transfers.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelScheduledTransfer = `-- name: CancelScheduledTransfer :one
UPDATE scheduled_transfers
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND executed_at IS NULL
RETURNING id, transfer_id, scheduled_at, executed_at, created_at
`

func (q *Queries) CancelScheduledTransfer(ctx context.Context, id pgtype.UUID) (ScheduledTransfer, error) {
	row := q.db.QueryRow(ctx, cancelScheduledTransfer, id)
	var i ScheduledTransfer
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createScheduledTransfer = `-- name: CreateScheduledTransfer :one
INSERT INTO scheduled_transfers
(transfer_id, scheduled_at)
VALUES ($1, $2)
RETURNING id, transfer_id, scheduled_at, executed_at, created_at
`

type CreateScheduledTransferParams struct {
	TransferID  pgtype.UUID        `json:"transfer_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateScheduledTransfer(ctx context.Context, arg CreateScheduledTransferParams) (ScheduledTransfer, error) {
	row := q.db.QueryRow(ctx, createScheduledTransfer, arg.TransferID, arg.ScheduledAt)
	var i ScheduledTransfer
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingScheduledTransfers = `-- name: GetPendingScheduledTransfers :many
SELECT id, transfer_id, scheduled_at, executed_at, created_at
FROM scheduled_transfers
WHERE scheduled_at <= $1
  AND executed_at IS NULL
`

func (q *Queries) GetPendingScheduledTransfers(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]ScheduledTransfer, error) {
	rows, err := q.db.Query(ctx, getPendingScheduledTransfers, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTransfer
	for rows.Next() {
		var i ScheduledTransfer
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.ScheduledAt,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledTransferById = `-- name: GetScheduledTransferById :one
SELECT id, transfer_id, scheduled_at, executed_at, created_at
FROM scheduled_transfers
WHERE id = $1
`

func (q *Queries) GetScheduledTransferById(ctx context.Context, id pgtype.UUID) (ScheduledTransfer, error) {
	row := q.db.QueryRow(ctx, getScheduledTransferById, id)
	var i ScheduledTransfer
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScheduledTransferByTransferId = `-- name: GetScheduledTransferByTransferId :one
SELECT id, transfer_id, scheduled_at, executed_at, created_at
FROM scheduled_transfers
WHERE transfer_id = $1
`

func (q *Queries) GetScheduledTransferByTransferId(ctx context.Context, transferID pgtype.UUID) (ScheduledTransfer, error) {
	row := q.db.QueryRow(ctx, getScheduledTransferByTransferId, transferID)
	var i ScheduledTransfer
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScheduledTransfersByUserId = `-- name: GetScheduledTransfersByUserId :many
SELECT st.id, st.transfer_id, st.scheduled_at, st.executed_at, st.created_at
FROM scheduled_transfers st
JOIN transfers t ON t.id = st.transfer_id
JOIN wallets w ON w.id = t.from_wallet_id
WHERE w.user_id = $1
  AND st.deleted_at IS NULL
ORDER BY st.scheduled_at DESC
`

func (q *Queries) GetScheduledTransfersByUserId(ctx context.Context, userID pgtype.UUID) ([]ScheduledTransfer, error) {
	rows, err := q.db.Query(ctx, getScheduledTransfersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTransfer
	for rows.Next() {
		var i ScheduledTransfer
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.ScheduledAt,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduledTransferExecuted = `-- name: MarkScheduledTransferExecuted :one
UPDATE scheduled_transfers
SET executed_at = NOW()
WHERE id = $1
RETURNING id, transfer_id, scheduled_at, executed_at, created_at
`

func (q *Queries) MarkScheduledTransferExecuted(ctx context.Context, id pgtype.UUID) (ScheduledTransfer, error) {
	row := q.db.QueryRow(ctx, markScheduledTransferExecuted, id)
	var i ScheduledTransfer
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}
