// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers
(
  from_wallet_id,
  to_wallet_id,
  amount,
  status,
  note,
  debit_transaction_id,
  credit_transaction_id)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7)
RETURNING id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
`

type CreateTransferParams struct {
	FromWalletID        pgtype.UUID    `json:"from_wallet_id"`
	ToWalletID          pgtype.UUID    `json:"to_wallet_id"`
	Amount              int64          `json:"amount"`
	Status              TransferStatus `json:"status"`
	Note                pgtype.Text    `json:"note"`
	DebitTransactionID  pgtype.UUID    `json:"debit_transaction_id"`
	CreditTransactionID pgtype.UUID    `json:"credit_transaction_id"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.FromWalletID,
		arg.ToWalletID,
		arg.Amount,
		arg.Status,
		arg.Note,
		arg.DebitTransactionID,
		arg.CreditTransactionID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransferById = `-- name: GetTransferById :one
SELECT id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
FROM transfers
WHERE id = $1
`

func (q *Queries) GetTransferById(ctx context.Context, id pgtype.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferById, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransferByIdWithUser = `-- name: GetTransferByIdWithUser :one
SELECT 
  t.id, t.from_wallet_id, t.to_wallet_id, t.amount, t.status, t.note,
  t.created_at, t.updated_at, t.deleted_at,
  t.debit_transaction_id, t.credit_transaction_id,
  fu.id as from_user_id, fu.full_name as from_user_full_name,
  tu.id as to_user_id, tu.full_name as to_user_full_name
FROM transfers t
LEFT JOIN wallets fw ON t.from_wallet_id = fw.id
LEFT JOIN users fu ON fw.user_id = fu.id
LEFT JOIN wallets tw ON t.to_wallet_id = tw.id
LEFT JOIN users tu ON tw.user_id = tu.id
WHERE t.id = $1
`

type GetTransferByIdWithUserRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FromWalletID        pgtype.UUID        `json:"from_wallet_id"`
	ToWalletID          pgtype.UUID        `json:"to_wallet_id"`
	Amount              int64              `json:"amount"`
	Status              TransferStatus     `json:"status"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DebitTransactionID  pgtype.UUID        `json:"debit_transaction_id"`
	CreditTransactionID pgtype.UUID        `json:"credit_transaction_id"`
	FromUserID          pgtype.UUID        `json:"from_user_id"`
	FromUserFullName    pgtype.Text        `json:"from_user_full_name"`
	ToUserID            pgtype.UUID        `json:"to_user_id"`
	ToUserFullName      pgtype.Text        `json:"to_user_full_name"`
}

func (q *Queries) GetTransferByIdWithUser(ctx context.Context, id pgtype.UUID) (GetTransferByIdWithUserRow, error) {
	row := q.db.QueryRow(ctx, getTransferByIdWithUser, id)
	var i GetTransferByIdWithUserRow
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.FromUserID,
		&i.FromUserFullName,
		&i.ToUserID,
		&i.ToUserFullName,
	)
	return i, err
}

const getTransfersByWalletId = `-- name: GetTransfersByWalletId :many
SELECT id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
FROM transfers
WHERE to_wallet_id = $1
   OR from_wallet_id = $1
`

func (q *Queries) GetTransfersByWalletId(ctx context.Context, toWalletID pgtype.UUID) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, getTransfersByWalletId, toWalletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromWalletID,
			&i.ToWalletID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.DebitTransactionID,
			&i.CreditTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransfersByWalletIdWithUser = `-- name: GetTransfersByWalletIdWithUser :many
SELECT 
  t.id, t.from_wallet_id, t.to_wallet_id, t.amount, t.status, t.note,
  t.created_at, t.updated_at, t.deleted_at,
  t.debit_transaction_id, t.credit_transaction_id,
  fu.id as from_user_id, fu.full_name as from_user_full_name,
  tu.id as to_user_id, tu.full_name as to_user_full_name
FROM transfers t
LEFT JOIN wallets fw ON t.from_wallet_id = fw.id
LEFT JOIN users fu ON fw.user_id = fu.id
LEFT JOIN wallets tw ON t.to_wallet_id = tw.id
LEFT JOIN users tu ON tw.user_id = tu.id
WHERE t.to_wallet_id = $1
   OR t.from_wallet_id = $1
`

type GetTransfersByWalletIdWithUserRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FromWalletID        pgtype.UUID        `json:"from_wallet_id"`
	ToWalletID          pgtype.UUID        `json:"to_wallet_id"`
	Amount              int64              `json:"amount"`
	Status              TransferStatus     `json:"status"`
	Note                pgtype.Text        `json:"note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DebitTransactionID  pgtype.UUID        `json:"debit_transaction_id"`
	CreditTransactionID pgtype.UUID        `json:"credit_transaction_id"`
	FromUserID          pgtype.UUID        `json:"from_user_id"`
	FromUserFullName    pgtype.Text        `json:"from_user_full_name"`
	ToUserID            pgtype.UUID        `json:"to_user_id"`
	ToUserFullName      pgtype.Text        `json:"to_user_full_name"`
}

func (q *Queries) GetTransfersByWalletIdWithUser(ctx context.Context, toWalletID pgtype.UUID) ([]GetTransfersByWalletIdWithUserRow, error) {
	rows, err := q.db.Query(ctx, getTransfersByWalletIdWithUser, toWalletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransfersByWalletIdWithUserRow
	for rows.Next() {
		var i GetTransfersByWalletIdWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FromWalletID,
			&i.ToWalletID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DebitTransactionID,
			&i.CreditTransactionID,
			&i.FromUserID,
			&i.FromUserFullName,
			&i.ToUserID,
			&i.ToUserFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferStatus = `-- name: UpdateTransferStatus :one
UPDATE transfers
SET status = $2
WHERE id = $1
RETURNING id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
`

type UpdateTransferStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status TransferStatus `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, updateTransferStatus, arg.ID, arg.Status)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransferWithTransactionId = `-- name: UpdateTransferWithTransactionId :one
UPDATE transfers
SET status = $2
WHERE credit_transaction_id = $1
   OR debit_transaction_id = $1
RETURNING id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
`

type UpdateTransferWithTransactionIdParams struct {
	CreditTransactionID pgtype.UUID    `json:"credit_transaction_id"`
	Status              TransferStatus `json:"status"`
}

func (q *Queries) UpdateTransferWithTransactionId(ctx context.Context, arg UpdateTransferWithTransactionIdParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, updateTransferWithTransactionId, arg.CreditTransactionID, arg.Status)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
