// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers
(id,
 from_wallet_id,
 to_wallet_id,
 amount,
 status,
 note,
 debit_transaction_id,
 credit_transaction_id)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8)
RETURNING id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
`

type CreateTransferParams struct {
	ID                  pgtype.UUID    `json:"id"`
	FromWalletID        pgtype.UUID    `json:"from_wallet_id"`
	ToWalletID          pgtype.UUID    `json:"to_wallet_id"`
	Amount              int64          `json:"amount"`
	Status              TransferStatus `json:"status"`
	Note                pgtype.Text    `json:"note"`
	DebitTransactionID  pgtype.UUID    `json:"debit_transaction_id"`
	CreditTransactionID pgtype.UUID    `json:"credit_transaction_id"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.ID,
		arg.FromWalletID,
		arg.ToWalletID,
		arg.Amount,
		arg.Status,
		arg.Note,
		arg.DebitTransactionID,
		arg.CreditTransactionID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransferById = `-- name: GetTransferById :one
SELECT id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
FROM transfers
WHERE id = $1
`

func (q *Queries) GetTransferById(ctx context.Context, id pgtype.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferById, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransferByWalletId = `-- name: GetTransferByWalletId :one
SELECT id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
FROM transfers
WHERE to_wallet_id = $1
   OR from_wallet_id = $1
`

func (q *Queries) GetTransferByWalletId(ctx context.Context, toWalletID pgtype.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByWalletId, toWalletID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :one
UPDATE transfers
SET status = $2
WHERE id = $1
RETURNING id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
`

type UpdateTransferStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status TransferStatus `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, updateTransferStatus, arg.ID, arg.Status)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransferWithTransactionId = `-- name: UpdateTransferWithTransactionId :one
UPDATE transfers
SET status = $2
WHERE credit_transaction_id = $1
   OR debit_transaction_id = $1
RETURNING id, from_wallet_id, to_wallet_id, amount, status, note, debit_transaction_id, credit_transaction_id, created_at, updated_at, deleted_at
`

type UpdateTransferWithTransactionIdParams struct {
	CreditTransactionID pgtype.UUID    `json:"credit_transaction_id"`
	Status              TransferStatus `json:"status"`
}

func (q *Queries) UpdateTransferWithTransactionId(ctx context.Context, arg UpdateTransferWithTransactionIdParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, updateTransferWithTransactionId, arg.CreditTransactionID, arg.Status)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.DebitTransactionID,
		&i.CreditTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
